before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake test_app"
script:
  - "export DISPLAY=:99.0"
  - "bundle exec rspec spec"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
